---
name: Devel-Modlist
version: 0.71
author:
  - 'Randy J. Ray <rjray@blackperl.com>'
abstract: Create lists of modules used by applications or other modules
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  CPAN: 1.8
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  Devel::Modlist:
    file: lib/Devel/Modlist.pm
    version: 0.71
  Devel::Modlist::QuietCPAN:
    file: lib/Devel/Modlist.pm
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
